// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Messenger is an autogenerated mock type for the Messenger type
type Messenger struct {
	mock.Mock
}
