// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	message "golang.org/x/text/message"

	store "github.com/rbicker/club/internal/store"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// CountMembers provides a mock function with given fields: ctx, printer, filterString
func (_m *Store) CountMembers(ctx context.Context, printer *message.Printer, filterString string) (int32, error) {
	ret := _m.Called(ctx, printer, filterString)

	var r0 int32
	if rf, ok := ret.Get(0).(func(context.Context, *message.Printer, string) int32); ok {
		r0 = rf(ctx, printer, filterString)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *message.Printer, string) error); ok {
		r1 = rf(ctx, printer, filterString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMember provides a mock function with given fields: ctx, printer, id
func (_m *Store) DeleteMember(ctx context.Context, printer *message.Printer, id string) error {
	ret := _m.Called(ctx, printer, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *message.Printer, string) error); ok {
		r0 = rf(ctx, printer, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMember provides a mock function with given fields: ctx, printer, id
func (_m *Store) GetMember(ctx context.Context, printer *message.Printer, id string) (*store.Member, error) {
	ret := _m.Called(ctx, printer, id)

	var r0 *store.Member
	if rf, ok := ret.Get(0).(func(context.Context, *message.Printer, string) *store.Member); ok {
		r0 = rf(ctx, printer, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *message.Printer, string) error); ok {
		r1 = rf(ctx, printer, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMemberByUserId provides a mock function with given fields: ctx, printer, userId
func (_m *Store) GetMemberByUserId(ctx context.Context, printer *message.Printer, userId string) (*store.Member, error) {
	ret := _m.Called(ctx, printer, userId)

	var r0 *store.Member
	if rf, ok := ret.Get(0).(func(context.Context, *message.Printer, string) *store.Member); ok {
		r0 = rf(ctx, printer, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *message.Printer, string) error); ok {
		r1 = rf(ctx, printer, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMembers provides a mock function with given fields: ctx, printer, filterString, orderBy, token, size
func (_m *Store) ListMembers(ctx context.Context, printer *message.Printer, filterString string, orderBy string, token string, size int32) (*[]store.Member, int32, string, error) {
	ret := _m.Called(ctx, printer, filterString, orderBy, token, size)

	var r0 *[]store.Member
	if rf, ok := ret.Get(0).(func(context.Context, *message.Printer, string, string, string, int32) *[]store.Member); ok {
		r0 = rf(ctx, printer, filterString, orderBy, token, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]store.Member)
		}
	}

	var r1 int32
	if rf, ok := ret.Get(1).(func(context.Context, *message.Printer, string, string, string, int32) int32); ok {
		r1 = rf(ctx, printer, filterString, orderBy, token, size)
	} else {
		r1 = ret.Get(1).(int32)
	}

	var r2 string
	if rf, ok := ret.Get(2).(func(context.Context, *message.Printer, string, string, string, int32) string); ok {
		r2 = rf(ctx, printer, filterString, orderBy, token, size)
	} else {
		r2 = ret.Get(2).(string)
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(context.Context, *message.Printer, string, string, string, int32) error); ok {
		r3 = rf(ctx, printer, filterString, orderBy, token, size)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// SaveMember provides a mock function with given fields: ctx, printer, member
func (_m *Store) SaveMember(ctx context.Context, printer *message.Printer, member *store.Member) (*store.Member, error) {
	ret := _m.Called(ctx, printer, member)

	var r0 *store.Member
	if rf, ok := ret.Get(0).(func(context.Context, *message.Printer, *store.Member) *store.Member); ok {
		r0 = rf(ctx, printer, member)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *message.Printer, *store.Member) error); ok {
		r1 = rf(ctx, printer, member)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
