// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/v1/club_service.proto

package clubv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// generic request containing just an id.
type IdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{0}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// generic list request.
type ListRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter               string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              string   `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{1}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type Member struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId               string               `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string               `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Mail                 string               `protobuf:"bytes,7,opt,name=mail,proto3" json:"mail,omitempty"`
	FirstName            string               `protobuf:"bytes,8,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,9,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,10,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Phone                string               `protobuf:"bytes,11,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              string               `protobuf:"bytes,12,opt,name=address,proto3" json:"address,omitempty"`
	Address2             string               `protobuf:"bytes,13,opt,name=address2,proto3" json:"address2,omitempty"`
	PostalCode           string               `protobuf:"bytes,14,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	City                 string               `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	Language             string               `protobuf:"bytes,16,opt,name=language,proto3" json:"language,omitempty"`
	Juristic             bool                 `protobuf:"varint,17,opt,name=juristic,proto3" json:"juristic,omitempty"`
	Organisation         string               `protobuf:"bytes,18,opt,name=organisation,proto3" json:"organisation,omitempty"`
	Website              string               `protobuf:"bytes,19,opt,name=website,proto3" json:"website,omitempty"`
	OrganisationType     string               `protobuf:"bytes,20,opt,name=organisation_type,json=organisationType,proto3" json:"organisation_type,omitempty"`
	Inactive             bool                 `protobuf:"varint,21,opt,name=inactive,proto3" json:"inactive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{2}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Member) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Member) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Member) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Member) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Member) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Member) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *Member) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Member) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Member) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *Member) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Member) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Member) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *Member) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Member) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Member) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Member) GetJuristic() bool {
	if m != nil {
		return m.Juristic
	}
	return false
}

func (m *Member) GetOrganisation() string {
	if m != nil {
		return m.Organisation
	}
	return ""
}

func (m *Member) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Member) GetOrganisationType() string {
	if m != nil {
		return m.OrganisationType
	}
	return ""
}

func (m *Member) GetInactive() bool {
	if m != nil {
		return m.Inactive
	}
	return false
}

type ListMembersResponse struct {
	Members              []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	NextPageToken        string    `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	PageSize             int32     `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalSize            int32     `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListMembersResponse) Reset()         { *m = ListMembersResponse{} }
func (m *ListMembersResponse) String() string { return proto.CompactTextString(m) }
func (*ListMembersResponse) ProtoMessage()    {}
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{3}
}

func (m *ListMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersResponse.Unmarshal(m, b)
}
func (m *ListMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersResponse.Marshal(b, m, deterministic)
}
func (m *ListMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersResponse.Merge(m, src)
}
func (m *ListMembersResponse) XXX_Size() int {
	return xxx_messageInfo_ListMembersResponse.Size(m)
}
func (m *ListMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersResponse proto.InternalMessageInfo

func (m *ListMembersResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *ListMembersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListMembersResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListMembersResponse) GetTotalSize() int32 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

type UpdateMemberRequest struct {
	Member               *Member               `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	FieldMask            *field_mask.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateMemberRequest) Reset()         { *m = UpdateMemberRequest{} }
func (m *UpdateMemberRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMemberRequest) ProtoMessage()    {}
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{4}
}

func (m *UpdateMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMemberRequest.Unmarshal(m, b)
}
func (m *UpdateMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMemberRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMemberRequest.Merge(m, src)
}
func (m *UpdateMemberRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMemberRequest.Size(m)
}
func (m *UpdateMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMemberRequest proto.InternalMessageInfo

func (m *UpdateMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *UpdateMemberRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Mail                 string               `protobuf:"bytes,5,opt,name=mail,proto3" json:"mail,omitempty"`
	Language             string               `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Password             string               `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	Confirmed            bool                 `protobuf:"varint,8,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Roles                []string             `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *User) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *User) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	FieldMask            *field_mask.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{6}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type ChangePasswordRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{7}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ConfirmMailRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmMailRequest) Reset()         { *m = ConfirmMailRequest{} }
func (m *ConfirmMailRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmMailRequest) ProtoMessage()    {}
func (*ConfirmMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{8}
}

func (m *ConfirmMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmMailRequest.Unmarshal(m, b)
}
func (m *ConfirmMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmMailRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmMailRequest.Merge(m, src)
}
func (m *ConfirmMailRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmMailRequest.Size(m)
}
func (m *ConfirmMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmMailRequest proto.InternalMessageInfo

func (m *ConfirmMailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ForgotPasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Mail                 string   `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{9}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ForgotPasswordRequest) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

type ResetPasswordRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{10}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Group struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Roles                []string             `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Members              []string             `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{11}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Group) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Group) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

type UpdateGroupRequest struct {
	Group                *Group                `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	FieldMask            *field_mask.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateGroupRequest) Reset()         { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()    {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{12}
}

func (m *UpdateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupRequest.Unmarshal(m, b)
}
func (m *UpdateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupRequest.Merge(m, src)
}
func (m *UpdateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupRequest.Size(m)
}
func (m *UpdateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupRequest proto.InternalMessageInfo

func (m *UpdateGroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UpdateGroupRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type ListGroupsResponse struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalSize            int32    `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0552a1f6c3547835, []int{13}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ListGroupsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func (m *ListGroupsResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListGroupsResponse) GetTotalSize() int32 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func init() {
	proto.RegisterType((*IdRequest)(nil), "club.v1.IdRequest")
	proto.RegisterType((*ListRequest)(nil), "club.v1.ListRequest")
	proto.RegisterType((*Member)(nil), "club.v1.Member")
	proto.RegisterType((*ListMembersResponse)(nil), "club.v1.ListMembersResponse")
	proto.RegisterType((*UpdateMemberRequest)(nil), "club.v1.UpdateMemberRequest")
	proto.RegisterType((*User)(nil), "club.v1.User")
	proto.RegisterType((*UpdateUserRequest)(nil), "club.v1.UpdateUserRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "club.v1.ChangePasswordRequest")
	proto.RegisterType((*ConfirmMailRequest)(nil), "club.v1.ConfirmMailRequest")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "club.v1.ForgotPasswordRequest")
	proto.RegisterType((*ResetPasswordRequest)(nil), "club.v1.ResetPasswordRequest")
	proto.RegisterType((*Group)(nil), "club.v1.Group")
	proto.RegisterType((*UpdateGroupRequest)(nil), "club.v1.UpdateGroupRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "club.v1.ListGroupsResponse")
}

func init() {
	proto.RegisterFile("api/proto/v1/club_service.proto", fileDescriptor_0552a1f6c3547835)
}

var fileDescriptor_0552a1f6c3547835 = []byte{
	// 1134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x5f, 0x73, 0xdb, 0x44,
	0x10, 0x8f, 0x1d, 0xff, 0x5d, 0x39, 0x49, 0x73, 0x49, 0xca, 0x61, 0xb7, 0x24, 0xd5, 0x30, 0x25,
	0xc0, 0x8c, 0x43, 0xc2, 0x13, 0x43, 0x07, 0x26, 0x71, 0x69, 0x5a, 0x86, 0x40, 0xc7, 0xa4, 0x2f,
	0xbc, 0x68, 0x64, 0x6b, 0xed, 0x1c, 0x91, 0x75, 0xaa, 0xee, 0x9c, 0xe0, 0x0e, 0x1f, 0x86, 0x07,
	0x1e, 0x78, 0xe3, 0xb3, 0xf0, 0x79, 0x78, 0x61, 0xee, 0x4e, 0x92, 0x65, 0x59, 0x4e, 0x1f, 0x3a,
	0xc3, 0xf4, 0xed, 0x76, 0xf7, 0xb7, 0x7b, 0xbb, 0xb7, 0xbb, 0x3f, 0x09, 0xf6, 0xdd, 0x90, 0x1d,
	0x85, 0x11, 0x97, 0xfc, 0xe8, 0xe6, 0xf8, 0x68, 0xe8, 0x4f, 0x07, 0x8e, 0xc0, 0xe8, 0x86, 0x0d,
	0xb1, 0xab, 0xb5, 0xa4, 0xae, 0x74, 0xdd, 0x9b, 0xe3, 0x76, 0x67, 0xcc, 0xf9, 0xd8, 0x47, 0x03,
	0x1e, 0x4c, 0x47, 0x47, 0x38, 0x09, 0xe5, 0xcc, 0xa0, 0xda, 0x07, 0x79, 0xe3, 0x88, 0xa1, 0xef,
	0x39, 0x13, 0x57, 0x5c, 0xc7, 0x88, 0xfd, 0x3c, 0x42, 0xb2, 0x09, 0x0a, 0xe9, 0x4e, 0x42, 0x03,
	0xb0, 0x3b, 0xd0, 0x7c, 0xe1, 0xf5, 0xf1, 0xf5, 0x14, 0x85, 0x24, 0x9b, 0x50, 0x66, 0x1e, 0x2d,
	0x1d, 0x94, 0x0e, 0x9b, 0xfd, 0x32, 0xf3, 0xec, 0xdf, 0xc1, 0xfa, 0x81, 0x09, 0x99, 0x98, 0x3b,
	0xd0, 0x0c, 0xdd, 0x31, 0x3a, 0x82, 0xbd, 0x41, 0x8d, 0xaa, 0xf6, 0x1b, 0x4a, 0xf1, 0x33, 0x7b,
	0x83, 0xe4, 0x21, 0x80, 0x36, 0x4a, 0x7e, 0x8d, 0x01, 0x2d, 0xeb, 0x18, 0x1a, 0x7e, 0xa9, 0x14,
	0xe4, 0x3e, 0xd4, 0x46, 0xcc, 0x97, 0x18, 0xd1, 0x75, 0x6d, 0x8a, 0x25, 0xf2, 0x21, 0x34, 0x78,
	0xe4, 0x61, 0xe4, 0x0c, 0x66, 0xb4, 0xa2, 0x2d, 0x75, 0x2d, 0x9f, 0xcd, 0xec, 0xbf, 0xab, 0x50,
	0xbb, 0xc0, 0xc9, 0x00, 0xa3, 0x7c, 0x62, 0xe4, 0x2b, 0x80, 0x61, 0x84, 0xae, 0x44, 0xcf, 0x71,
	0xa5, 0xbe, 0xcc, 0x3a, 0x69, 0x77, 0x4d, 0xad, 0xdd, 0xa4, 0xd6, 0xee, 0x65, 0x52, 0x6b, 0xbf,
	0x19, 0xa3, 0x4f, 0xa5, 0x72, 0x9d, 0x86, 0x5e, 0xe2, 0xba, 0xfe, 0x76, 0xd7, 0x18, 0x7d, 0x2a,
	0xc9, 0x07, 0x50, 0x9f, 0x0a, 0x8c, 0x1c, 0xe6, 0xc5, 0xa9, 0xd6, 0x94, 0xf8, 0xc2, 0x23, 0x6d,
	0x68, 0xa8, 0x53, 0xe0, 0x4e, 0x90, 0x56, 0xb5, 0x25, 0x95, 0x95, 0x2d, 0x74, 0x85, 0xb8, 0xe5,
	0x91, 0x47, 0x6b, 0xc6, 0x96, 0xc8, 0x84, 0x40, 0x65, 0xe2, 0x32, 0x9f, 0xd6, 0xb5, 0x5e, 0x9f,
	0xd5, 0x3b, 0x8e, 0x58, 0x24, 0xa4, 0xa3, 0xa3, 0x35, 0xcc, 0x3b, 0x6a, 0xcd, 0x8f, 0x2a, 0x5c,
	0x07, 0x9a, 0xbe, 0x9b, 0x58, 0x9b, 0x26, 0x9e, 0x52, 0x68, 0xe3, 0x37, 0xb0, 0xa1, 0x72, 0x75,
	0xf8, 0xc8, 0x19, 0xb0, 0x48, 0x5e, 0x51, 0x78, 0x6b, 0x79, 0x96, 0x72, 0xf8, 0x69, 0x74, 0xa6,
	0xe0, 0x64, 0x17, 0xaa, 0xe1, 0x15, 0x0f, 0x90, 0x5a, 0x3a, 0xb0, 0x11, 0x08, 0x85, 0xba, 0xeb,
	0x79, 0x11, 0x0a, 0x41, 0x5b, 0xa6, 0x43, 0xb1, 0xa8, 0x6a, 0x8b, 0x8f, 0x27, 0x74, 0xc3, 0xe4,
	0x92, 0xc8, 0x64, 0x1f, 0xac, 0x90, 0x0b, 0xe9, 0xfa, 0xce, 0x90, 0x7b, 0x48, 0x37, 0xb5, 0x19,
	0x8c, 0xaa, 0xc7, 0x3d, 0x54, 0xc5, 0x0f, 0x99, 0x9c, 0xd1, 0x2d, 0x53, 0xbc, 0x3a, 0xab, 0x80,
	0xbe, 0x1b, 0x8c, 0xa7, 0xee, 0x18, 0xe9, 0xbd, 0xa4, 0x38, 0x23, 0x2b, 0xdb, 0xaf, 0xd3, 0x88,
	0x09, 0xc9, 0x86, 0x74, 0xfb, 0xa0, 0x74, 0xd8, 0xe8, 0xa7, 0x32, 0xb1, 0xa1, 0xc5, 0xa3, 0xb1,
	0x1b, 0x30, 0xe1, 0x4a, 0xc6, 0x03, 0x4a, 0xb4, 0xef, 0x82, 0x4e, 0x95, 0x71, 0x8b, 0x03, 0xc1,
	0x24, 0xd2, 0x1d, 0x53, 0x46, 0x2c, 0x92, 0xcf, 0x61, 0x3b, 0x8b, 0x74, 0xe4, 0x2c, 0x44, 0xba,
	0xab, 0x31, 0xf7, 0xb2, 0x86, 0xcb, 0x59, 0xa8, 0xd3, 0x60, 0x81, 0x3b, 0x94, 0xec, 0x06, 0xe9,
	0x9e, 0x49, 0x23, 0x91, 0xed, 0x3f, 0x4b, 0xb0, 0xa3, 0x16, 0xc6, 0x4c, 0xad, 0xe8, 0xa3, 0x08,
	0x79, 0x20, 0x90, 0x7c, 0x0a, 0xf5, 0x89, 0x51, 0xd1, 0xd2, 0xc1, 0xfa, 0xa1, 0x75, 0xb2, 0xd5,
	0x8d, 0xf7, 0xbb, 0x6b, 0xa0, 0xfd, 0xc4, 0x4e, 0x1e, 0xc3, 0x56, 0x80, 0xbf, 0x49, 0x67, 0x69,
	0x97, 0x36, 0x94, 0xfa, 0x65, 0xba, 0x4f, 0x0b, 0xbb, 0xb8, 0xbe, 0xbc, 0x8b, 0x92, 0xab, 0xa7,
	0xd7, 0xd6, 0x8a, 0xb6, 0x36, 0xb5, 0x46, 0x99, 0xed, 0x19, 0xec, 0xbc, 0xd2, 0x43, 0x1d, 0x5f,
	0x1e, 0xaf, 0xf7, 0x27, 0x50, 0x33, 0x59, 0xe8, 0x45, 0x2b, 0x48, 0x32, 0x36, 0xab, 0x15, 0x9a,
	0x13, 0xcd, 0xca, 0xed, 0x7b, 0xa6, 0x20, 0x17, 0xae, 0xb8, 0x56, 0xe3, 0x1b, 0x1f, 0xed, 0xbf,
	0xca, 0x50, 0x79, 0x25, 0xde, 0x9b, 0x8d, 0xce, 0x2e, 0x6e, 0x25, 0xb7, 0xb8, 0xc9, 0x72, 0x56,
	0x33, 0xcb, 0x99, 0x9d, 0xcf, 0xda, 0xf2, 0x7c, 0xa6, 0x8b, 0x5e, 0xcf, 0x2d, 0xfa, 0x03, 0x68,
	0x0e, 0x79, 0x30, 0x62, 0xd1, 0x04, 0x3d, 0xbd, 0xd3, 0x8d, 0xfe, 0x5c, 0xa1, 0xd6, 0x2e, 0xe2,
	0x3e, 0x0a, 0xda, 0x3c, 0x58, 0x57, 0x6b, 0xa7, 0x05, 0xfb, 0x35, 0x6c, 0x9b, 0x2e, 0xa9, 0xf7,
	0x4a, 0x7a, 0xf4, 0x08, 0x2a, 0x2a, 0xc1, 0xb8, 0x43, 0x1b, 0x69, 0x87, 0x34, 0x46, 0x9b, 0xde,
	0xa5, 0x3b, 0x13, 0xd8, 0xeb, 0x5d, 0xb9, 0xc1, 0x18, 0x5f, 0xc6, 0x89, 0xaf, 0xf8, 0x30, 0x90,
	0x47, 0xd0, 0xe2, 0xbe, 0xe7, 0xa4, 0xf5, 0x9a, 0x11, 0xb5, 0xb8, 0xef, 0x25, 0x9e, 0x0a, 0x12,
	0xe0, 0xed, 0x1c, 0x62, 0x68, 0xdf, 0x0a, 0xf0, 0x36, 0x81, 0xd8, 0x9f, 0x01, 0xe9, 0x99, 0x47,
	0xb8, 0x70, 0x99, 0x9f, 0xdc, 0xb5, 0x0b, 0x55, 0x33, 0xf7, 0xe6, 0x3a, 0x23, 0xd8, 0xe7, 0xb0,
	0xf7, 0x8c, 0x47, 0x63, 0x2e, 0xf3, 0xa9, 0x65, 0x5b, 0x58, 0x5a, 0xd1, 0xc2, 0xf2, 0xbc, 0x85,
	0xf6, 0x73, 0xd8, 0xed, 0xa3, 0xc0, 0xa5, 0x38, 0x85, 0xd7, 0x2e, 0x34, 0xb5, 0xbc, 0xd8, 0x54,
	0xfb, 0x9f, 0x12, 0x54, 0xcf, 0x23, 0x3e, 0x0d, 0xdf, 0x93, 0x61, 0x26, 0x50, 0xc9, 0x0c, 0xb2,
	0x3e, 0xcf, 0x47, 0xab, 0x9a, 0x19, 0x2d, 0x45, 0x85, 0x09, 0x1f, 0xd5, 0xb4, 0x3e, 0x11, 0xed,
	0x29, 0x10, 0x33, 0x74, 0xba, 0xb0, 0xe4, 0x6d, 0x3e, 0x86, 0xea, 0x58, 0xc9, 0xf1, 0xd8, 0x6d,
	0xa6, 0x63, 0x67, 0x50, 0xc6, 0xf8, 0x2e, 0x83, 0xf7, 0x47, 0x09, 0x88, 0x22, 0x4e, 0x1d, 0x6f,
	0xce, 0x9b, 0x8f, 0xa1, 0xa6, 0x43, 0x27, 0xb4, 0x99, 0xbf, 0x38, 0xb6, 0xfe, 0x1f, 0xa4, 0x79,
	0xf2, 0x6f, 0x0d, 0x2a, 0x3d, 0x7f, 0x3a, 0x20, 0x3d, 0xf3, 0x53, 0x14, 0x73, 0x3c, 0xd9, 0x4d,
	0x73, 0xca, 0xfc, 0x2a, 0xb5, 0x1f, 0x2c, 0x68, 0x73, 0xdf, 0x03, 0x7b, 0x8d, 0x9c, 0x40, 0xf3,
	0x1c, 0x63, 0x3d, 0x21, 0x29, 0x38, 0xfd, 0x15, 0x6b, 0xe7, 0xc9, 0x57, 0xfb, 0xb4, 0x7a, 0x7a,
	0x4e, 0x62, 0xb7, 0x3c, 0xa4, 0xc8, 0xe7, 0x5b, 0x68, 0x65, 0xa9, 0x9e, 0xcc, 0xf3, 0x2a, 0xf8,
	0x02, 0x14, 0x05, 0x78, 0x02, 0xad, 0xa7, 0xe8, 0x63, 0x1a, 0xa0, 0x28, 0xd7, 0xfb, 0x4b, 0x4d,
	0xfe, 0x4e, 0xfd, 0xa4, 0xda, 0x6b, 0xe4, 0x7b, 0xd8, 0x5c, 0x24, 0x14, 0xf2, 0x51, 0xea, 0x5f,
	0xc8, 0x34, 0x77, 0xc4, 0x7a, 0x0a, 0x56, 0x86, 0x2d, 0x48, 0x67, 0x1e, 0x68, 0x89, 0x43, 0xee,
	0xce, 0x68, 0x91, 0x47, 0x32, 0x19, 0x15, 0x12, 0xcc, 0x1d, 0xb1, 0x9e, 0xc3, 0xc6, 0x02, 0x95,
	0x90, 0x87, 0x69, 0xa8, 0x22, 0x8a, 0xb9, 0x23, 0xd2, 0x29, 0xc0, 0x7c, 0xfc, 0x57, 0x8c, 0x54,
	0x67, 0x41, 0xbb, 0xb8, 0x29, 0xf6, 0x1a, 0xf9, 0x02, 0x1a, 0xe7, 0x68, 0xd4, 0x85, 0x4d, 0xca,
	0xed, 0x8e, 0xbd, 0x46, 0x8e, 0xc0, 0x32, 0xf3, 0x14, 0x93, 0xd8, 0x22, 0xa0, 0xc0, 0xe1, 0x09,
	0x58, 0x19, 0x72, 0xc8, 0x74, 0x60, 0x99, 0x32, 0x0a, 0xbc, 0xbf, 0x06, 0xcb, 0x4c, 0xd2, 0xea,
	0x1c, 0x57, 0x3e, 0xd0, 0x59, 0xe3, 0x97, 0x9a, 0x82, 0xdf, 0x1c, 0x0f, 0x6a, 0xda, 0xf6, 0xe5,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x33, 0xc9, 0x95, 0x43, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClubClient is the client API for Club service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClubClient interface {
	// members
	// List members.
	ListMembers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	// Get a member.
	GetMember(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Member, error)
	// Creates a member.
	CreateMember(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error)
	// Updates a member.
	UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*Member, error)
	// Deletes a user.
	DeleteMember(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// gooser
	// Change password.
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Confirm Mail.
	ConfirmMail(ctx context.Context, in *ConfirmMailRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Forgot Password.
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Reset Password.
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// List groups.
	ListGroups(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	// Gets a group.
	GetGroup(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Group, error)
	// Creates a group.
	CreateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error)
	// Updates a group.
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*Group, error)
	// Deletes a group.
	DeleteGroup(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type clubClient struct {
	cc grpc.ClientConnInterface
}

func NewClubClient(cc grpc.ClientConnInterface) ClubClient {
	return &clubClient{cc}
}

func (c *clubClient) ListMembers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, "/club.v1.Club/ListMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) GetMember(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/club.v1.Club/GetMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) CreateMember(ctx context.Context, in *Member, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/club.v1.Club/CreateMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) UpdateMember(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*Member, error) {
	out := new(Member)
	err := c.cc.Invoke(ctx, "/club.v1.Club/UpdateMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) DeleteMember(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/club.v1.Club/DeleteMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/club.v1.Club/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) ConfirmMail(ctx context.Context, in *ConfirmMailRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/club.v1.Club/ConfirmMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/club.v1.Club/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/club.v1.Club/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) ListGroups(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/club.v1.Club/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) GetGroup(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/club.v1.Club/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) CreateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/club.v1.Club/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/club.v1.Club/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clubClient) DeleteGroup(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/club.v1.Club/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClubServer is the server API for Club service.
type ClubServer interface {
	// members
	// List members.
	ListMembers(context.Context, *ListRequest) (*ListMembersResponse, error)
	// Get a member.
	GetMember(context.Context, *IdRequest) (*Member, error)
	// Creates a member.
	CreateMember(context.Context, *Member) (*Member, error)
	// Updates a member.
	UpdateMember(context.Context, *UpdateMemberRequest) (*Member, error)
	// Deletes a user.
	DeleteMember(context.Context, *IdRequest) (*empty.Empty, error)
	// gooser
	// Change password.
	ChangePassword(context.Context, *ChangePasswordRequest) (*empty.Empty, error)
	// Confirm Mail.
	ConfirmMail(context.Context, *ConfirmMailRequest) (*empty.Empty, error)
	// Forgot Password.
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*empty.Empty, error)
	// Reset Password.
	ResetPassword(context.Context, *ResetPasswordRequest) (*empty.Empty, error)
	// List groups.
	ListGroups(context.Context, *ListRequest) (*ListGroupsResponse, error)
	// Gets a group.
	GetGroup(context.Context, *IdRequest) (*Group, error)
	// Creates a group.
	CreateGroup(context.Context, *Group) (*Group, error)
	// Updates a group.
	UpdateGroup(context.Context, *UpdateGroupRequest) (*Group, error)
	// Deletes a group.
	DeleteGroup(context.Context, *IdRequest) (*empty.Empty, error)
}

// UnimplementedClubServer can be embedded to have forward compatible implementations.
type UnimplementedClubServer struct {
}

func (*UnimplementedClubServer) ListMembers(ctx context.Context, req *ListRequest) (*ListMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembers not implemented")
}
func (*UnimplementedClubServer) GetMember(ctx context.Context, req *IdRequest) (*Member, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMember not implemented")
}
func (*UnimplementedClubServer) CreateMember(ctx context.Context, req *Member) (*Member, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMember not implemented")
}
func (*UnimplementedClubServer) UpdateMember(ctx context.Context, req *UpdateMemberRequest) (*Member, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMember not implemented")
}
func (*UnimplementedClubServer) DeleteMember(ctx context.Context, req *IdRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMember not implemented")
}
func (*UnimplementedClubServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedClubServer) ConfirmMail(ctx context.Context, req *ConfirmMailRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmMail not implemented")
}
func (*UnimplementedClubServer) ForgotPassword(ctx context.Context, req *ForgotPasswordRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (*UnimplementedClubServer) ResetPassword(ctx context.Context, req *ResetPasswordRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (*UnimplementedClubServer) ListGroups(ctx context.Context, req *ListRequest) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}
func (*UnimplementedClubServer) GetGroup(ctx context.Context, req *IdRequest) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (*UnimplementedClubServer) CreateGroup(ctx context.Context, req *Group) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedClubServer) UpdateGroup(ctx context.Context, req *UpdateGroupRequest) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (*UnimplementedClubServer) DeleteGroup(ctx context.Context, req *IdRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}

func RegisterClubServer(s *grpc.Server, srv ClubServer) {
	s.RegisterService(&_Club_serviceDesc, srv)
}

func _Club_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/ListMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).ListMembers(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/GetMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).GetMember(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_CreateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Member)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).CreateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/CreateMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).CreateMember(ctx, req.(*Member))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_UpdateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).UpdateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/UpdateMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).UpdateMember(ctx, req.(*UpdateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/DeleteMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).DeleteMember(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_ConfirmMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).ConfirmMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/ConfirmMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).ConfirmMail(ctx, req.(*ConfirmMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).ListGroups(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).GetGroup(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).CreateGroup(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Club_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClubServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.v1.Club/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClubServer).DeleteGroup(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Club_serviceDesc = grpc.ServiceDesc{
	ServiceName: "club.v1.Club",
	HandlerType: (*ClubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMembers",
			Handler:    _Club_ListMembers_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _Club_GetMember_Handler,
		},
		{
			MethodName: "CreateMember",
			Handler:    _Club_CreateMember_Handler,
		},
		{
			MethodName: "UpdateMember",
			Handler:    _Club_UpdateMember_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _Club_DeleteMember_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Club_ChangePassword_Handler,
		},
		{
			MethodName: "ConfirmMail",
			Handler:    _Club_ConfirmMail_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _Club_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _Club_ResetPassword_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _Club_ListGroups_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _Club_GetGroup_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Club_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _Club_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _Club_DeleteGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/club_service.proto",
}
