// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de": &dictionary{index: deIndex, data: deData},
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s has a length of 0":                                      4,
	"%s is not a valid mail address":                            18,
	"%s is not a valid phone number":                            19,
	"date of birth cannot be in the future":                     21,
	"either userId, username or mail address are already taken": 22,
	"error while looking for duplicates":                        23,
	"error while querying %s":                                   10,
	"error while saving":                                        15,
	"error while sending mail: %s":                              32,
	"gooser connection failed":                                  25,
	"internal error while building filter":                      0,
	"invalid field mask: %s":                                    27,
	"invalid id":                                                16,
	"invalid id '%s'":                                           14,
	"invalid language '%s'":                                     20,
	"invalid page token given":                                  5,
	"invalid rsql filter string '%s': %s":                       3,
	"orderBy field has a length of 0":                           1,
	"pagination filter and given filters do not match":          6,
	"pagination orderBy and given orderBy do not match":         7,
	"password cannot be changed using the UpdateMember function, use ChangePassword instead": 30,
	"password must have a length of at least 7":                                              24,
	"permission denied":                                              26,
	"required field(s) missing: %s":                                  34,
	"the request was canceled by the client":                         8,
	"unable to count %s":                                             9,
	"unable to count members":                                        13,
	"unable to decode document":                                      11,
	"unable to find %s document with id %s":                          17,
	"unable to find document":                                        12,
	"unable to merge":                                                28,
	"unable to search next document while creating pagination token": 2,
	"unexpected value while looking for required fields":             33,
	"you are not allowed to change the mail address for other users": 31,
	"you are not allowed to change the user id":                      29,
}

var deIndex = []uint32{ // 36 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
} // Size: 168 bytes

const deData string = ""

var enIndex = []uint32{ // 36 elements
	// Entry 0 - 1F
	0x00000000, 0x00000025, 0x00000045, 0x00000084,
	0x000000ae, 0x000000c6, 0x000000df, 0x00000110,
	0x00000142, 0x00000169, 0x0000017f, 0x0000019a,
	0x000001b4, 0x000001cc, 0x000001e4, 0x000001f7,
	0x0000020a, 0x00000215, 0x00000241, 0x00000263,
	0x00000285, 0x0000029e, 0x000002c4, 0x000002fe,
	0x00000321, 0x0000034b, 0x00000364, 0x00000376,
	0x00000390, 0x000003a0, 0x000003ca, 0x00000421,
	// Entry 20 - 3F
	0x00000460, 0x00000480, 0x000004b3, 0x000004d4,
} // Size: 168 bytes

const enData string = "" + // Size: 1236 bytes
	"\x02internal error while building filter\x02orderBy field has a length o" +
	"f 0\x02unable to search next document while creating pagination token" +
	"\x02invalid rsql filter string '%[1]s': %[2]s\x02%[1]s has a length of 0" +
	"\x02invalid page token given\x02pagination filter and given filters do n" +
	"ot match\x02pagination orderBy and given orderBy do not match\x02the req" +
	"uest was canceled by the client\x02unable to count %[1]s\x02error while " +
	"querying %[1]s\x02unable to decode document\x02unable to find document" +
	"\x02unable to count members\x02invalid id '%[1]s'\x02error while saving" +
	"\x02invalid id\x02unable to find %[1]s document with id %[2]s\x02%[1]s i" +
	"s not a valid mail address\x02%[1]s is not a valid phone number\x02inval" +
	"id language '%[1]s'\x02date of birth cannot be in the future\x02either u" +
	"serId, username or mail address are already taken\x02error while looking" +
	" for duplicates\x02password must have a length of at least 7\x02gooser c" +
	"onnection failed\x02permission denied\x02invalid field mask: %[1]s\x02un" +
	"able to merge\x02you are not allowed to change the user id\x02password c" +
	"annot be changed using the UpdateMember function, use ChangePassword ins" +
	"tead\x02you are not allowed to change the mail address for other users" +
	"\x02error while sending mail: %[1]s\x02unexpected value while looking fo" +
	"r required fields\x02required field(s) missing: %[1]s"

	// Total table size 1572 bytes (1KiB); checksum: FD67C9B0
